spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://13.235.208.227"  # Match frontend URL exactly
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS   # Allow preflight requests
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: product-service
          uri: http://13.235.208.227:8090
          predicates:
            - Path=/product/**
          filters:
            - SetResponseHeader=Access-Control-Allow-Origin, https://13.235.208.227
            - SetResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
            - SetResponseHeader=Access-Control-Allow-Headers, *
            - SetResponseHeader=Access-Control-Allow-Credentials, true

        # Handle CORS Preflight Requests
        - id: preflight-requests
          uri: no://op
          predicates:
            - Method=OPTIONS
          filters:
            - SetResponseHeader=Access-Control-Allow-Origin, https://13.235.208.227
            - SetResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
            - SetResponseHeader=Access-Control-Allow-Headers, *
            - SetResponseHeader=Access-Control-Allow-Credentials, true
            - SetResponseStatus=200

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mypassword
    key-store-type: PKCS12
    key-alias: mysslkey
    key-password: mypassword