spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://13.235.208.227:80"
              - "http://13.235.208.227"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://13.200.154.116:8082
          predicates:
            - Path=/user/**
          filters:
            - SetResponseHeader=Content-Security-Policy,"script-src 'self'"

        - id: product-service
          uri: http://13.200.154.116:8081
          predicates:
            - Path=/product/**
          filters:
            - SetResponseHeader=Content-Security-Policy,"script-src 'self'"

        - id: inventory-service
          uri: http://13.203.142.39:8081
          predicates:
            - Path=/inventory/**
          filters:
            - SetResponseHeader=Content-Security-Policy,"script-src 'self'"

        - id: order-service
          uri: http://13.203.142.39:8083
          predicates:
            - Path=/order/**
          filters:
            - SetResponseHeader=Content-Security-Policy,"script-src 'self'"
  application:
    name: ecom-api-gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Debug logs for Gateway routing and filters
    org.springframework.web: DEBUG           # Debug logs for HTTP request handling
    org.springframework.http: DEBUG

