spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://3.109.190.106:80/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - SetResponseHeader=Content-Security-Policy,"script-src 'self'"

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - SetResponseHeader=Content-Security-Policy,"script-src 'self'"
  application:
    name: ecom-api-gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Debug logs for Gateway routing and filters
    org.springframework.web: DEBUG           # Debug logs for HTTP request handling
    org.springframework.http: DEBUG

