spring:
  application:
    name: ecom-api-gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

cloud:
  gateway:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:3000"
            - "http://3.109.190.106:80/"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
          allowedHeaders:
            - "*"
          allowCredentials: true
    routes:
      - id: user-service
        uri: http://13.200.154.116:8082
        predicates:
          - Path=/user/**
        filters:
          - RewritePath=/user(?<segment>/.*), /user{segment}
          - CustomRequestHeader
          - SetResponseHeader=Content-Security-Policy,"script-src 'self'"

      - id: product-service
        uri: http://13.200.154.116:8081
        predicates:
          - Path=/product/**
        filters:
          - RewritePath=/product(?<segment>.*), /product{segment}
          - CustomRequestHeader
          - SetResponseHeader=Content-Security-Policy,"script-src 'self'"